name: flutter_settings_bar_design
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^1.0.5
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  readmore: ^3.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map_location_marker: ^9.0.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  http: ^1.2.1
  syncfusion_flutter_maps: ^26.1.38
  flutter_map_marker_popup: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/ble.png
    - assets/fruit_and_vegetables.png
    - assets/gavebånd.png
    - assets/køkkenrulle.png
    - assets/madaffald.png
    - assets/notDefined.png
    - assets/pap.png
    - assets/papvin.png
    - assets/pasta.png
    - assets/pizzabox.png
    - assets/restaffald.png
    - assets/støvsugerpose.png
    - assets/skyr.PNG
    - assets/mælk.png
    - assets/æg.png
    - assets/mutti.png
    - assets/kaffe.png
    - assets/export-1.geojson
    - assets/export-2.geojson
    - assets/export-6.geojson
    - assets/ris.png
    - assets/ost.png
    - assets/brød.png
    - assets/plast.png
    - assets/glas.png
    - assets/farligt_affald.png
    - assets/papir.png
    - assets/metal.png
    - assets/tekstilaffald.png
    - assets/afdækningsplast.png
    - assets/aviser.png
    - assets/batterier.png 
    - assets/bobleplast.png
    - assets/hundefoder.png
    - assets/husholdningsfilm.png
    - assets/kødbakker.png
    - assets/mel.png
    - assets/ødelagttøj.png
    - assets/perler.png
    - assets/plastiktallerkener.png
    - assets/poly.png
    - assets/slikposer.png
    - assets/tebreve.png
    - assets/tefiltre.png
    - assets/tøj.png
    - assets/magasiner.png
    - assets/tegninger.png
    - assets/toiletrulle.png
    - assets/papbakker.png
    - assets/drikkeglas.png
    - assets/juiceflasker.png
    - assets/glasskår.png
    - assets/konservesglas.png
    - assets/sodadåse.png
    - assets/kapsler.png
    - assets/kniv.png
    - assets/osteklinger.png
    - assets/gryder.png
    - assets/knapbatteri.png
    - assets/pærer.png
    - assets/afkalk.png
    - assets/pærer.png
    - assets/vitaminglas.png
    - assets/metallåg.png
    - assets/afløb.png
    - assets/neglefil.png
    - assets/brugtbenzindunk.png
    - assets/eddikesyre.png
    - assets/fugemasse.png
    - assets/eltandbørste.png
    - assets/makeuprester.png
    - assets/neglelakfjerner.png
    - assets/madpapir.png
    - assets/bind.png
    - assets/cigaretskod.png
    - assets/kondomer.png
    - assets/plaster.png
    - assets/kattegrus.png
    - assets/toiletboerster.png
    - assets/mundbind.png
    - assets/knæklys.png
    - assets/linser.png
    - assets/skum.png
    - assets/pander.png
    - assets/lim.png
    - assets/syltetøj.png
    - assets/øl.png
    - assets/knapbatteri.png
    - assets/kondomer.png
    - assets/hundeposer.png
    - assets/håndsprit.png
    - assets/hårspray.png
    - assets/hår.png
    - assets/chipsposer.png
    - assets/benzin.png
    - assets/juiceflasker.png
    - assets/husholdningsfilm.png
    - assets/mapper.png
    - assets/medicinplast.png
    - assets/smør.png
    - assets/låg.png
    - assets/katelog.png
    - assets/papbakke.png
    - assets/smør.png
    - assets/nøgler.png
    - assets/pærer.png
    - assets/afløb.png
    - assets/klorin.png
    - assets/acetone.png
    - assets/næsespray.png
    - assets/toiletrens.png
    - assets/engangsklude.png
    - assets/gaffatape.png
    - assets/knæklys.png
    - assets/knæklys.png
    - assets/sandpapir.png
    - assets/bestik.png
    - assets/astma.png
    - assets/sovs.png
    - assets/spraydåser.png
    - assets/malingsrester.png
    - assets/led.png
    - assets/urtepotter.png
    - assets/affaldssække.png
    - assets/deoroll.png
    - assets/deospray.png
    - assets/is.png
    - assets/shampoo.png
    - assets/håndklæder.png
    - assets/breve.png
    - assets/bon.png
    - assets/postit.png
    - assets/æggebakker.png
    - assets/vin.png
    - assets/sølvpapir.png
    - assets/kniv.png
    - assets/alubakke.png
    - assets/søm.png
    - assets/bekæmpelse.png
    - assets/klorin.png
    - assets/tyggegummi.png
    - assets/kuglepind.png
    - assets/betalingskort.png
    - assets/vatpinde.png
    - assets/vådservietter.png
    - assets/tennisbolde.png
    - assets/snavsetpapir.png